site_name: "GMT 簡易教學手冊"
site_description: "GMT 簡易教學手冊 | 編者: Po-Chin Tseng, Sean Li-Shin Ho"
repo_name: sean0921/gmt_tutorials_simple
repo_url: https://github.com/sean0921/gmt_tutorials_simple
theme:
  name: material
  language: zh-TW
  features:
    - content.tabs.link
nav:
  - '總覽': index.md
  - 'GMT介紹及安裝': intro_install.md
  - '網路資源及配套軟體': net_software.md
  - '第零章: 基本概念及預設值': basic_defaults.md
  - '第一章: 製作地圖: 地理投影法': projection.md
  - '第二章: XY散佈圖: 其他投影法': xy_figure.md
  - '第三章: 等高線圖及剖面': contour_profile.md
  - '第四章: 地形圖與色階': topography_cpt.md
  - '第五章: 地震活動性與機制解': seismicity_meca.md
  - '第六章: 向量與速度場': vector_velocity.md
  - '第七章: 台灣地理資訊': taiwan_geography.md
  - '第八章: 直方、圓餅、三元圖': histo_pie_ternary.md
  - '第九章: 三維空間視圖': three_dimension.md
  - '第十章: 地質圖': geology_map.md
copyright: 'Project maintained by jimmytseng79, sean0921.  License: CC-BY-SA 3.0'
markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
