name: Mkdocs Build and Deploy

on: 
  push:
    branches: [master]

jobs:
  pages:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Taipei"
      CNAME: "simplegmt.clam.moe"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install poetry-core
        run: |
          python -m pip install --upgrade pip poetry_core setuptools
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          python -m pip install .
      - name: Build
        run: |
          mkdocs build
      - name: Change CNAME
        run: |
          echo "${CNAME}" | tee ./site/CNAME
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages  # deploying branch
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
